name: CI/CD

env:
  REGISTRY: quay.io
  REGISTRY_USERNAME: dabreadman
  APP_NAME: "covid-app"
  TAG: ""

  # Application environment variables
  VUE_APP_COVIDAPIKEY: ${{ secrets.VUE_APP_COVIDAPIKEY }}
  VUE_APP_POPULATIONAPIKEY: ${{ secrets.VUE_APP_POPULATIONAPIKEY }}

on:
  push:
    branches:
      - main
    paths:
      - "covid-vue-app"
      - ".github/workflows"
  pull_request:
  workflow_dispatch:

jobs:
  dev-deployment:
    name: Build and deploy to OpenShift Dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./covid-vue-app
    environment: development

    steps:
      - uses: actions/checkout@v2

      - name: Determine app name
        if: env.APP_NAME == ''
        run: |
          echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV

      - name: Determine tag by version
        if: env.TAG == ''
        run: |
          echo "TAG=$(jq -r .version package.json)" | tee -a $GITHUB_ENV

      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build image, run lint/test
        run: docker build . --file Dockerfile --build-arg VUE_APP_COVIDAPIKEY=${{ env.VUE_APP_COVIDAPIKEY }} --build-arg VUE_APP_POPULATIONAPIKEY=${{ env.VUE_APP_POPULATIONAPIKEY }} --tag ${{ env.REGISTRY }}/${{ env.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ env.TAG }}
